### ISSUE TITLE
What is the best best practice for rendering JSON / JS responses?

### ISSUE THREAD

**Issue by TangRufus** [envato/aldous#13]
I found no JSON / JS templates in the demo app / the read me. 
What is the best best practice for rendering JSON / JS responses while using Aldous?

**Comment by skorks** [comment]
For rendering JSON for APIs etc, you simply use the `View` objects e.g.:

```ruby
class SomeApi::ShowView < BaseView
  def template_data
    {
      json: {
        hello: 'world',
      }
    }
  end
end
```

This is nice cause you can write specs for the JSON objects you build, if you want to, and test them via the `template_data` method.

In its simplest form, the `template_data` method simply returns a hash that gets fed to the standard Rails `render` method (this happens inside Aldous https://github.com/envato/aldous/blob/master/lib/aldous/respondable/renderable.rb#L45). So whatever `render` supports will work http://apidock.com/rails/ActionController/Base/render.

**Comment by TangRufus** [comment]
Thanks!
