### ISSUE TITLE
Catch unexpected errors

### ISSUE THREAD

**Issue by holgersindbaek** [envato/aldous#18]
I'm using your Aldous for my Rails API and so far I'm really loving it. I'm using Raygun to catch unexpected errors and I'm not sure whether Aldous will catch these errors before they have a change of being sent to Raygun. Is there any method in the "Aldous::Service" module that gets called if an unexpected error occurs?

**Comment by skorks** [comment]
Hi,

So if I understand correctly, you want to send errors to an external service when they occur in an aldous service, here is what you need to know.

When you construct a service using `build` the object that gets returned is actually a `Aldous::Service::Wrapper`. The `perform` method in here is as follows:

```ruby  
      def perform
        perform!
      rescue => e
        Aldous::LoggingWrapper.log(e.cause || e)
        Aldous::Service::Result::Failure.new(default_result_data.merge(errors: [e]))
      end
```

What you're interested in is `Aldous::LoggingWrapper.log`. If you look in there you'll see `::Aldous.config.error_reporter.report(error)`.

So when you call `perform` on a service if an error occurs, it will be reported via the error reporter you configure in the Aldous configuration in the initializer, see https://github.com/envato/aldous#configuring-aldous. By default this doesn't do anything, but if you supply an object of your own, it will do whatever you implement in the `report` method (e.g. sending it to an external service etc.).

Hope this helps.

**Comment by holgersindbaek** [comment]
That's exactly what I needed. Thanks! 

This is my Aldous initializer for reference:

    # Create error reporter
    module Aldous
      class ErrorReporter
        def self.report(e, data = {})
          Raygun.track_exception(e)
          nil
        end
      end
    end

    # Set error reporter
    Aldous.configuration do |aldous|
      aldous.error_reporter = Aldous::ErrorReporter
    end

**Comment by skorks** [comment]
That looks fine, just an FYI though, you don't have to define the `ErrorReporter` in the Aldous namespace, everything will work just fine if you do it in your own namespace e.g.:

```ruby
# Create error reporter
module MyNamespace
  class ErrorReporter
    def self.report(e, data = {})
      Raygun.track_exception(e)
      nil
    end
  end
end

# Set error reporter
Aldous.configuration do |aldous|
  aldous.error_reporter = MyNamespace::ErrorReporter
end
```
